# Generated by Django 2.0.7 on 2018-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180816_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori'),
        ),
    ]
