# Generated by Django 2.0.7 on 2018-08-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180819_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_auther',
            new_name='comment_author',
        ),
    ]
