# Generated by Django 2.0.7 on 2018-08-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180819_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='', verbose_name='Makaleye Fotoğraf Ekleyin'),
        ),
    ]
